### ISSUE TITLE
Golang服务端发布实例方法,dotnet客户端调用的问题

### ISSUE THREAD

**Issue by czyt** [hprose/hprose-golang#101]
Golang服务端代码如下
```go
package main

import (
	"log"
	"net"

	"github.com/hprose/hprose-golang/v3/rpc"
)

type DeviceInvoker interface {
	GetDeviceName()[]byte
	GetDeviceProto()[]byte
}

type FakeDevice struct {}

func (f FakeDevice) GetDeviceName() []byte {
	return []byte("Test Device")
}

func (f FakeDevice) GetDeviceProto() []byte {
	return []byte("Test Proto")
}

func main() {
	service := rpc.NewService()
	service.Codec = rpc.NewServiceCodec(rpc.WithDebug(true))
	service.AddInstanceMethods(&FakeDevice{})
	server, err := net.Listen("tcp", "127.0.0.1:8412")
	if err != nil {
		log.Fatalln(err)
	}
	defer server.Close()
	err = service.Bind(server)
	if err != nil {
		log.Fatalln(err)
	}
	for  {
		
	}
}

```
疑问如下

- golang服务器发布方法时是否支持发布接口并注入实现接口的实例，这个不知道怎么写
- dotnet客户端，如果服务端实例方法，那么客户端使用一个自定接口 能否实现对应的转换，我的dotnet客户端代码如下
``` dotnet
class Program
    {
        
         interface IDeviceInvoker
        {
           public byte[] GetDeviceName();
           public byte[] GetDeviceProto();
        }
        static void Main(string[] args)
        {
            
            var client = new Client("tcp://127.0.0.1");
            var log = new Log();
            client.Use(log.IOHandler).Use(log.InvokeHandler);
           var proxy = client.UseService<IDeviceInvoker>();
           var deviceName = proxy.GetDeviceName();
           
           // var invoke = client.Invoke<byte[]>("GetDeviceName", null);
           //  Console.WriteLine(System.Text.Encoding.UTF8.GetString(invoke));
        }
    }
```
被注释的代码，调用正常，但是没被注释的调用失败，报错
```
Unhandled exception. System.TypeLoadException: Type '$Proxy0' from assembly '$Assembly0, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' is attempting to implement an inaccessible interface
.
   at System.Reflection.Emit.TypeBuilder.CreateTypeNoLock()
   at System.Reflection.Emit.TypeBuilder.CreateTypeInfo()
   at Hprose.RPC.Proxy.GetProxyWithoutCache(Type[] interfaces)
   at Hprose.RPC.Proxy.<>c.<GetProxy>b__30_0(ProxyKey proxykey)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Hprose.RPC.Proxy.GetProxy(Type[] interfaces)
   at Hprose.RPC.Proxy.NewInstance(Type[] interfaces, IInvocationHandler handler)
   at Hprose.RPC.Client.UseService[T](String ns)
   at hproseClient.Program.Main(String[] args) in F:\go\hproseTest\client\hproseClient\hproseClient\Program.cs:line 21

```

**Comment by andot** [comment]
在 dotnet 里面使用 public 的 interface 就可以了。

**Comment by czyt** [comment]
> 在 dotnet 里面使用 public 的 interface 就可以了。

谢谢，确实是接口定义的作用域问题。已经解决
